export const LINNSY_ERROR_CODES = {
  LLM_MODEL_NOT_FOUND: 'LINNSY_LLM_MODEL_NOT_FOUND',
  LLM_MODEL_PROFILE_INVALID: 'LINNSY_LLM_MODEL_PROFILE_INVALID',
  LLM_PROTOCOL_UNSUPPORTED: 'LINNSY_LLM_PROTOCOL_UNSUPPORTED',
  LLM_CODEC_INVALID_PAYLOAD: 'LINNSY_LLM_CODEC_INVALID_PAYLOAD',
  LLM_PROVIDER_AUTH_MISSING: 'LINNSY_LLM_PROVIDER_AUTH_MISSING',
  LLM_MODEL_CREDENTIAL_REQUIRED: 'LINNSY_LLM_MODEL_CREDENTIAL_REQUIRED',
  LLM_PROVIDER_UNSUPPORTED: 'LINNSY_LLM_PROVIDER_UNSUPPORTED',
  LLM_PROVIDER_UNAVAILABLE: 'LINNSY_LLM_PROVIDER_UNAVAILABLE',
  LLM_PROVIDER_REQUEST_FAILED: 'LINNSY_LLM_PROVIDER_REQUEST_FAILED',
  SESSION_NOT_FOUND: 'LINNSY_SESSION_NOT_FOUND',
  CHANNEL_NOT_STARTED: 'LINNSY_CHANNEL_NOT_STARTED',
  DEFINITION_NOT_FOUND: 'LINNSY_DEFINITION_NOT_FOUND',
  DEFINITION_REGISTER_AT_RUNTIME: 'LINNSY_DEFINITION_REGISTER_AT_RUNTIME',
  DEFINITION_INVALID: 'LINNSY_DEFINITION_INVALID',
  RUN_ABANDONED: 'LINNSY_RUN_ABANDONED',
  RUN_EXECUTOR_FAILED: 'LINNSY_RUN_EXECUTOR_FAILED',
  AUTH_DENIED: 'LINNSY_AUTH_DENIED',
  NOTIFICATION_PROACTIVE_UNIMPLEMENTED: 'LINNSY_NOTIFICATION_PROACTIVE_UNIMPLEMENTED',
  NOTIFICATION_DELIVERY_FAILED: 'LINNSY_NOTIFICATION_DELIVERY_FAILED',
  NOTIFICATION_NO_TARGET: 'LINNSY_NOTIFICATION_NO_TARGET',
  TASK_TRANSITION_INVALID: 'LINNSY_TASK_TRANSITION_INVALID',
  TASK_NOT_FOUND: 'LINNSY_TASK_NOT_FOUND',
  HTTP_BEARER_REQUIRED: 'LINNSY_HTTP_BEARER_REQUIRED',
  CONVERSATION_CREATE_INVALID: 'LINNSY_CONVERSATION_CREATE_INVALID',
  CONVERSATION_NOT_FOUND: 'LINNSY_CONVERSATION_NOT_FOUND',
  CONVERSATION_DELETE_TERMINAL_BOUND: 'LINNSY_CONVERSATION_DELETE_TERMINAL_BOUND',
  CONVERSATION_ARCHIVE_TERMINAL_BOUND: 'LINNSY_CONVERSATION_ARCHIVE_TERMINAL_BOUND',
  CONVERSATION_DELETE_HAS_ACTIVE_RUN: 'LINNSY_CONVERSATION_DELETE_HAS_ACTIVE_RUN',
  CONVERSATION_TITLE_INVALID: 'LINNSY_CONVERSATION_TITLE_INVALID',
  TOOL_RESULT_OVERSIZE: 'LINNSY_TOOL_RESULT_OVERSIZE',
  WORKSPACE_INIT_FAILED: 'LINNSY_WORKSPACE_INIT_FAILED',
  INTERNAL_AGENT_SPAWN_FAILED: 'LINNSY_INTERNAL_AGENT_SPAWN_FAILED',
  TASK_REDELEGATE_LIMIT: 'LINNSY_TASK_REDELEGATE_LIMIT',
  TASK_CANNOT_CONTINUE: 'LINNSY_TASK_CANNOT_CONTINUE',
  TASK_LOCATOR_INVALID: 'LINNSY_TASK_LOCATOR_INVALID',
  TASK_LOCATOR_KIND_NOT_SUPPORTED: 'LINNSY_TASK_LOCATOR_KIND_NOT_SUPPORTED',
  EXTERNAL_VENDOR_NOT_AVAILABLE: 'LINNSY_EXTERNAL_VENDOR_NOT_AVAILABLE',
  EXTERNAL_DISPATCH_FAILED: 'LINNSY_EXTERNAL_DISPATCH_FAILED',
  EXTERNAL_SESSION_NOT_FOUND: 'LINNSY_EXTERNAL_SESSION_NOT_FOUND',
  CRON_JOB_NOT_FOUND: 'LINNSY_CRON_JOB_NOT_FOUND',
  CRON_SCHEDULE_INVALID: 'LINNSY_CRON_SCHEDULE_INVALID',
  CRON_LOCK_UNAVAILABLE: 'LINNSY_CRON_LOCK_UNAVAILABLE',
  MEMORY_SCOPE_NOT_WRITABLE: 'LINNSY_MEMORY_SCOPE_NOT_WRITABLE',
  MEMORY_BUILTIN_PROTECTED: 'LINNSY_MEMORY_BUILTIN_PROTECTED',
  MEMORY_BODY_TOO_LARGE: 'LINNSY_MEMORY_BODY_TOO_LARGE'
} as const;

export class LinnsyError extends Error {
  public readonly code: string;
  public readonly recoverable: boolean;

  public constructor(code: string, message: string, recoverable: boolean) {
    super(message);
    this.name = 'LinnsyError';
    this.code = code;
    this.recoverable = recoverable;
  }
}
